const SPREADSHEET_ID='YOUR_SPREADSHEET_ID_HERE';
function doGet(e){try{const data={ok:true,books:read()};const cb=e&&e.parameter&&e.parameter.callback;if(cb&&/^[A-Za-z_$][\w$]*(\.[A-Za-z_$][\w$]*)*$/.test(cb))return ContentService.createTextOutput(cb+'('+JSON.stringify(data)+')').setMimeType(ContentService.MimeType.JAVASCRIPT);return out(data)}catch(x){const data={ok:false,error:String(x)};const cb=e&&e.parameter&&e.parameter.callback;if(cb&&/^[A-Za-z_$][\w$]*(\.[A-Za-z_$][\w$]*)*$/.test(cb))return ContentService.createTextOutput(cb+'('+JSON.stringify(data)+')').setMimeType(ContentService.MimeType.JAVASCRIPT);return out(data)}}
function doPost(e){try{const raw=e.postData&&e.postData.contents||'';const b=JSON.parse(e.parameter&&e.parameter.payload||raw||'{}');if(b.action!=='sync'||!Array.isArray(b.books))throw Error('Expected action=sync and books');write(b.books);return out({ok:true,count:b.books.length})}catch(x){return out({ok:false,error:String(x)})}}
function read(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),a=[];sheet(ss,'Owned','Physical',a);sheet(ss,'To Buy','Wishlist',a);return a}
function normalizeFormat(format){const raw=String(format==null?'':format).replace(/[\u00a0\u2007\u202f]/g,' ').replace(/&amp;/gi,'&').trim();if(!raw)return '';const low=raw.toLowerCase().normalize('NFKC').replace(/[‐-―−]/g,'-').replace(/[&+/,|]/g,' and ').replace(/\s+/g,' ').trim();if(low==='wishlist')return 'Wishlist';if(low==='book & kindle'||low==='book and kindle'||low==='physical and kindle'||low==='kindle and physical'||low==='both')return 'Book & Kindle';if(['book','physical','print','paperback','hardcover','hardback','paper'].includes(low))return 'Physical';if(['kindle','ebook','e-book','digital'].includes(low))return 'Kindle';const hasKindle=/\bkindle\b|\be-?book\b|\bebook\b|\bdigital\b/.test(low);const hasPhysical=/\bphysical\b|\bbook\b|\bprint\b|\bpaperback\b|\bhardcover\b|\bhardback\b|\bpaper\b/.test(low);if(hasKindle&&hasPhysical)return 'Book & Kindle';if(hasKindle)return 'Kindle';if(hasPhysical)return 'Physical';return raw}
function sheet(ss,name,def,a){const sh=ss.getSheetByName(name);if(!sh)throw Error('Missing sheet '+name);const v=sh.getDataRange().getValues();if(!v.length)return;const h=v[0].map(x=>String(x).replace(/[\u00a0\u2007\u202f]/g,' ').replace(/\s+/g,' ').trim()),hl=h.map(x=>x.toLowerCase()),c=n=>{let target=String(n).replace(/[\u00a0\u2007\u202f]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();let i=hl.indexOf(target);if(i>=0)return i;return hl.findIndex(x=>x.replace(/[^a-z0-9]+/g,'')===target.replace(/[^a-z0-9]+/g,''));};for(let i=1;i<v.length;i++){if(!v[i][c('Title')])continue;let s=c('Series')>=0?String(v[i][c('Series')]||''):'';if(s==='No')s='';let f=def;if(def==='Physical'&&c('Format')>=0)f=normalizeFormat(v[i][c('Format')]);a.push({id:'sheet-'+name+'-'+i,title:String(v[i][c('Title')]),author:c('Author')>=0?String(v[i][c('Author')]||''):'',genre:c('Genre')>=0?String(v[i][c('Genre')]||''):'',series:s,seriesNo:c('Series No')>=0?String(v[i][c('Series No')]||'').replace(/\.0$/,''):'',format:f,formatRaw:(c('Format')>=0?String(v[i][c('Format')]||''):f),readingStatus:c('A Status')>=0?String(v[i][c('A Status')]||''):'',isbn:c('ISBN')>=0?String(v[i][c('ISBN')]||''):'',addedAt:''})}}

function write(bs){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);writeOwned(ss.getSheetByName('Owned'),bs.filter(b=>b.format!=='Wishlist'));writeBuy(ss.getSheetByName('To Buy'),bs.filter(b=>b.format==='Wishlist'))}
function bookKey(b){const isbn=String(b.isbn||'').replace(/[^0-9Xx]/g,'');if(isbn)return 'isbn:'+isbn;return 'book:'+String(b.title||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()+'|'+String(b.author||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function writeOwned(sh,bs){const h=['Author','Title','Genre','Series','Series No','A Status','S Status','Format'];const map={};bs.forEach(b=>{b={...b,format:normalizeFormat(b.format)};const k=bookKey(b);if(!map[k])map[k]={...b};else{const x=map[k],fmt=normalizeFormat(x.format)+' '+normalizeFormat(b.format);x.format=fmt.toLowerCase().includes('kindle')&&(fmt.toLowerCase().includes('physical')||fmt.toLowerCase().includes('book'))?'Book & Kindle':fmt.toLowerCase().includes('kindle')?'Kindle':'Physical';if(!x.coverUrl)x.coverUrl=b.coverUrl;if(!x.readingStatus)x.readingStatus=b.readingStatus||'Unread';}});const r=Object.values(map).map(b=>{b.format=normalizeFormat(b.format);return [b.author||'',b.title||'',b.genre||'',b.series&&String(b.series).toLowerCase()!=='no'?b.series:'No',b.seriesNo&&String(b.seriesNo).toLowerCase()!=='standalone'?b.seriesNo:'Standalone',['Read','DNF','Unread'].includes(String(b.readingStatus||''))?String(b.readingStatus):'Unread','Unread',b.format==='Book & Kindle'?'Book & Kindle':b.format==='Kindle'?'Kindle':'Book']});sh.clearContents();sh.getRange(1,1,1,h.length).setValues([h]);if(r.length)sh.getRange(2,1,r.length,h.length).setValues(r)}
function writeBuy(sh,bs){const h=['Author','Title','Genre','Series','Series No'],r=bs.map(b=>[b.author||'',b.title||'',b.genre||'',b.series&&String(b.series).toLowerCase()!=='no'?b.series:'No',b.seriesNo&&String(b.seriesNo).toLowerCase()!=='standalone'?b.seriesNo:'Standalone']);sh.clearContents();sh.getRange(1,1,1,h.length).setValues([h]);if(r.length)sh.getRange(2,1,r.length,h.length).setValues(r)}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
